/**
 * Configuration options for the Sigil library.
 *
 * These options control runtime validation, inheritance checks, label autofill behavior.
 */
export interface SigilOptions {
  /**
   * Validation rule applied to sigil labels before registration.
   *
   * - A function receives the label and must return `true` if valid.
   * - A `RegExp` must match the label.
   * - `null` disables validation entirely.
   *
   * Defaults to `null`.
   */
  labelValidation?: ((label: string) => boolean) | RegExp | null;

  /**
   * Skips the runtime check that prevents subclasses from inheriting
   * the same sigil label as their ancestors.
   *
   * When `false` (default), extending a sigil class without
   * using `WithSigil(newLabel)` decorator will throw an error if the label
   * is reused and `OPTIONS.autofillLabels` is set to `false`.
   *
   * Set this to `true` only if you intentionally want subclasses to inherit labels
   * from their ancestors (this weakens the uniqueness guarantees).
   *
   * WARNING:
   * Disabling inheritanceCheck removes guaranties by 'Sigil' or unique label for
   * each class and allow multiple child classes to use the same label which can
   * result on false 'isOfType' result. this options should be used in debugging
   * only to silence all errors but never in production.
   */
  skipLabelInheritanceCheck?: boolean;

  /**
   * When enabled, non-decorated subclasses that would otherwise inherit an ancestor's label
   * will be assigned an autogenerated random label (so that explicit labels stay unique).
   */
  autofillLabels?: boolean;
}

/** -----------------------------------------
 *  Main options object
 * ----------------------------------------- */

/**
 * Defined SigilOptions used in the library.
 *
 * @internal
 */
export const OPTIONS: Required<SigilOptions> = {
  labelValidation: null,
  skipLabelInheritanceCheck: false,
  autofillLabels: false,
};

/**
 * Update runtime options for the Sigil library.
 * Call this early during application startup if you want non-default behavior.
 *
 * @param opts - Partial options to merge into the global `OPTIONS` object.
 */
export const updateOptions = (opts: SigilOptions): void => {
  for (const [k, v] of Object.entries(opts)) (OPTIONS as any)[k] = v;
};

/**
 * Default runtime options used by the Sigil library.
 *
 * @internal
 */
const DEFAULT_OPTIONS: Required<SigilOptions> = {
  labelValidation: null,
  skipLabelInheritanceCheck: false,
  autofillLabels: false,
};

// populate 'OPTIONS' with DEFAULT_OPTIONS
updateOptions(DEFAULT_OPTIONS);

/** -----------------------------------------
 *  Label validation
 * ----------------------------------------- */

/**
 * Label validation regex. Labels must follow the pattern
 * `@scope/package.ClassName` where `ClassName` begins with an uppercase
 * letter. This avoids collisions across packages and helps debugging.
 *
 * It's advised to use this regex in 'SigilOptions.labelValidation'.
 */
export const DEFAULT_LABEL_REGEX = /^@[\w-]+(?:\/[\w-]+)*\.[A-Z][A-Za-z0-9]*$/;
