/** Dev check */
const DEV = process.env.NODE_ENV !== 'production';

/**
 * Configuration options for the Sigil library.
 *
 * These options control runtime validation, inheritance checks, label autofill behavior,
 * and whether duplicate labels are permitted globally.
 *
 * Note: these options are read by runtime code during class decoration and inheritance
 * checks. Some behaviors (like `skipLabelInheritanceCheck`) are meant primarily for
 * development/test scenarios and may weaken type/identity guarantees when changed.
 */
export interface SigilOptions {
  /**
   * Validation rule applied to sigil labels before registration.
   *
   * - A function receives the label and must return `true` if valid.
   * - A `RegExp` must match the label.
   * - `null` disables validation entirely.
   *
   * Defaults to `null`.
   */
  labelValidation?: ((label: string) => boolean) | RegExp | null;

  /**
   * Skips the runtime check that prevents subclasses from inheriting
   * the same sigil label as their ancestors.
   *
   * When `false` (default), extending a sigil class without
   * using `WithSigil(newLabel)` decorator will throw an error if the label
   * is reused and `OPTIONS.autofillLabels` is set to `false`.
   *
   * Set this to `true` only if you intentionally want subclasses to inherit labels
   * from their ancestors (this weakens the uniqueness guarantees).
   */
  skipLabelInheritanceCheck?: boolean;

  /**
   * When enabled, non-decorated subclasses that would otherwise inherit an ancestor's label
   * will be assigned an autogenerated random label (so that explicit labels stay unique).
   */
  autofillLabels?: boolean;

  /**
   * Marker used internally to control dev only checks to optimize performace while preserving
   * consistency for things like inheritance checks.
   * defaults to 'process.env.NODE_ENV !== "production'.
   */
  devMarker?: boolean;
}

/**
 * Default runtime options used by the Sigil library.
 *
 * These values may be mutated by calling `updateOptions` at app startup.
 *
 * @internal
 */
export const OPTIONS: Required<SigilOptions> = {
  labelValidation: null,
  skipLabelInheritanceCheck: false,
  autofillLabels: false,
  devMarker: DEV,
};

/**
 * Update runtime options for the Sigil library.
 * Call this early during application startup if you want non-default behavior.
 *
 * Example:
 * ```ts
 * updateOptions({ autofillLabels: true, labelValidation: /^@[\w-]+\/[\w-]+\.[A-Za-z0-9]+$/ });
 * ```
 *
 * @param opts - Partial options to merge into the global `OPTIONS` object.
 */
export const updateOptions = (opts: SigilOptions): void => {
  for (const [k, v] of Object.entries(opts)) (OPTIONS as any)[k] = v;
};

/**
 * Label validation regex. Labels must follow the pattern
 * `@scope/package.ClassName` where `ClassName` begins with an uppercase
 * letter. This avoids collisions across packages and helps debugging.
 *
 * It's advised to use this regex in 'SigilOptions.labelValidation'.
 */
export const DEFAULT_LABEL_REGEX = /^@[\w-]+(?:\/[\w-]+)*\.[A-Z][A-Za-z0-9]*$/;
