/** -----------------------------------------
 *  Types
 * ----------------------------------------- */

/**
 * Configuration options for the Sigil library.
 *
 * These options control runtime validation, inheritance checks, label autofill behavior.
 */
export interface SigilOptions {
  /**
   * Validation rule applied to sigil labels before registration.
   *
   * - A function receives the label and must return `true` if valid.
   * - A `RegExp` must match the label.
   * - `null` disables validation entirely.
   *
   * Defaults to `null`.
   */
  labelValidation?: ((label: string) => boolean) | RegExp | null;

  /**
   * When enabled, non-decorated subclasses that would otherwise inherit an ancestor's label
   * will be assigned an autogenerated random label (so that explicit labels stay unique).
   */
  autofillLabels?: boolean;

  /**
   * Option for Hot module reload set-ups, reload of files can result in class redefinition which will throw
   * duplicate label error, setting this to 'true' will disabel this error.
   * However as it disables unique label check bugs can appear if the same label is passed to two different
   * classes so set this to 'true' only when needed and ensure uniqueness of passed labels.
   */
  skipLabelUniquenessCheck?: boolean;
}

/** -----------------------------------------
 *  Internal options object
 * ----------------------------------------- */

/**
 * Defined SigilOptions used in the library.
 *
 * @internal
 */
export const OPTIONS: Required<SigilOptions> = {
  labelValidation: null,
  autofillLabels: true,
  skipLabelUniquenessCheck: false,
};

/** -----------------------------------------
 *  Update options
 * ----------------------------------------- */

/**
 * Update runtime options for the Sigil library.
 * Call this early during application startup if you want non-default behavior.
 *
 * @param opts - Partial options to merge into the global `OPTIONS` object.
 */
export const updateSigilOptions = (opts: SigilOptions): void => {
  if ('autofillLabels' in opts) {
    if (typeof opts.autofillLabels !== 'boolean')
      throw new Error("'updateSigilOptions.autofillLabels' must be boolean");
    OPTIONS.autofillLabels = opts.autofillLabels!;
  }

  if ('labelValidation' in opts) {
    const val = opts.labelValidation;
    if (val !== null && typeof val !== 'function' && !(val instanceof RegExp))
      throw new Error("'updateSigilOptions.labelValidation' must be null, function or RegExp");
    OPTIONS.labelValidation = val;
  }

  if ('skipLabelUniquenessCheck' in opts) {
    if (typeof opts.skipLabelUniquenessCheck !== 'boolean')
      throw new Error("'updateSigilOptions.skipLabelUniquenessCheck' must be boolean");
    OPTIONS.skipLabelUniquenessCheck = opts.skipLabelUniquenessCheck;
  }
};

/** -----------------------------------------
 *  Label validation
 * ----------------------------------------- */

/**
 * Label validation regex. Labels must follow the pattern
 * `@scope/package.ClassName` where `ClassName` begins with an uppercase
 * letter. This avoids collisions across packages and helps debugging.
 *
 * It's advised to use this regex in 'SigilOptions.labelValidation'.
 */
export const RECOMMENDED_LABEL_REGEX = /^@[\w-]+(?:\/[\w-]+)*\.[A-Z][A-Za-z0-9]*$/;

/** @deprecated - Use 'RECOMMENDED_LABEL_REGEX' instead, will be removed in v4 */
export const DEFAULT_LABEL_REGEX = RECOMMENDED_LABEL_REGEX;
